### ISSUE TITLE
Can't resolve './index'

### ISSUE THREAD

**Issue by zhangzhuang15** [zjxxxxxxxxx/open-editor#200]
There is a error message when I compile with webpack:
```txt
ERROR in ./node_modules/@open-editor/client/dist/client.mjs 3:2-19
Module not found: Error: Can't resolve './index' 
Did you mean 'index.js'?
BREAKING CHANGE: The request './index' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
```
And I check your source code at the position of `createClient.ts`， you write `import('./index')`，but node doesn't know which it is index.js or index.mjs or index.cjs ?

**Comment by zjxxxxxxxxx** [comment]
Thank you for your feedback. I don't know which version of webpack and nodejs you are using. I don't know how to reproduce this problem.

**Comment by zhangzhuang15** [comment]
Ok, I will try to provide a minimum reproduction link of it later, for some reason, it's not allowed for me to do that now. By the way, I used this tool to help me debug react app, it leaves me a pretty good impression, thanks for your work!

**Comment by zjxxxxxxxxx** [comment]
Thanks for the support!

**Comment by zhangzhuang15** [comment]
Check this [branch](https://github.com/zhangzhuang15/open-editor-webpack-react-bug-reproduce), get the reproduction. @zjxxxxxxxxx

**Comment by zjxxxxxxxxx** [comment]
OK, this issue will be resolved soon.
