### ISSUE TITLE
Does not provide an export named 'default' errors

### ISSUE THREAD

**Issue by anchan42** [zjxxxxxxxxx/open-editor#244]
I got error below on console:

index.mjs?v=f0c71643:1 Uncaught SyntaxError: The requested module '/node_modules/picomatch/index.js?v=f0c71643' does not provide an export named 'default' (at index.mjs?v=f0c71643:1:134)

The stack blits show just white screen.
![stack](https://github.com/user-attachments/assets/17965fa5-c956-432f-b1c0-afc28e425a58)

**Comment by zjxxxxxxxxx** [comment]
It's a problem with picomatch, I look for an alternative to fix it

**Comment by zjxxxxxxxxx** [comment]
I found a temporary solution

``` js 
...
optimizeDeps: {
  include: [
    'picomatch'
  ]
}
...
```

<img width="1682" alt="image" src="https://github.com/user-attachments/assets/31e5fcb4-854d-4e75-8688-56dcc19c790e">

**Comment by anchan42** [comment]
Thank you ! The error is gone now but I got this when clicking on the element. Probably because of the extra / in front of the C:?

![er](https://github.com/user-attachments/assets/07ae6883-5fc4-4bf2-b02b-178559619a73)

**Comment by zjxxxxxxxxx** [comment]
The situation is not good. I only have a macbook. I don't know how to reproduce this problem at the moment. It may take a while to solve it.

**Comment by anchan42** [comment]
No worries. Is there any options to customize the path?
I think if we take out the extra / in front of the C:, it should work.

**Comment by zjxxxxxxxxx** [comment]
There is no custom method. I installed an emulator that can reproduce this problem. I will take some time to fix it.

**Comment by anchan42** [comment]
> There is no custom method. I installed an emulator that can reproduce this problem. I will take some time to fix it.

Thank you. It would be a great help for me. 👍
